version: "3"

services:
  traefik:
    image: traefik:v1.7-alpine
    command:
      - --api
      - --docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
    networks:
      - HYDYCO_NETWORK

  hdydco_docs:
    image: hdydco_docs
    build: .
    networks:
      - HYDYCO_NETWORK
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hdydco_docs"
      - "traefik.frontend.rule=Host:hydyco.com"
      - "traefik.port=80"
      - "traefik.docker.network=HYDYCO_NETWORK"

networks:
  HYDYCO_NETWORK:
